name: Kali Linux VPS (LKHACKERS)
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt update && sudo apt install -y tmate
          sudo docker pull kalilinux/kali-rolling
          sudo docker run -d --name kali-vps kalilinux/kali-rolling sleep infinity
      - name: Connect
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          sleep 21600
